### ISSUE TITLE
Implement `Driver_LED_GetColor` Function

### ISSUE THREAD

**Issue by WDobert** [alanssitis/smart-air-hockey-table#121]
Any advanced visuals, such as "fade", require modifying previously set LED matrix colors instead of blindly overwriting.

Additional matrix state will need to be kept in RAM since reconstructing it from the data buffer would be drastically slower.

Recommend storing this state as an array of structs with 3 `uint8_t` members (r, g, b), and converting the setter/getter functions to pass it instead of `uint32_t`.

Recommend exposing `LED_MATRIX_WIDTH` and `LED_MATRIX_HEIGHT` in `driver_led.h`.

**Comment by benjamin-owen** [comment]
Probably unnecessarily reducing performance, we can simply have a 2nd buffer which is added to the first one.  This ensures sequential memory accesses (and less of them).

We could also keep a list of changes to be made.  This reduces processing time and only changes what needs to be changed.

**Comment by WDobert** [comment]
Closed in favor of #123
