### ISSUE TITLE
Verify PCB Functionality

### ISSUE THREAD

**Issue by WDobert** [alanssitis/smart-air-hockey-table#136]
- [x] Buck Converter
- [x] Microcontroller Communication
- [x] Debug LEDs
- [x] Reset Button
- [x] Rotary Encoder
- [x] LDRs
- [x] OLEDs
- [x] LED Matrix Channels
- [x] Hall Effect Polling
- [x] Blower Fan Relay

**Comment by benjamin-owen** [comment]
:nerd_face:
